# Message from speed test
Header header

# Current status of the test
string status_description

# Current status of the test
uint8 status

# Time of the test in iso format
string timestamp

# Client IP address used for the test
string client

# Server name used for the test
string server

# Ping in milliseconds
uint16 ping

# Download speed in bps
float32 download_speed

# Bytes received
uint32 bytes_received

# Upload speed in bps
float32 upload_speed

# Bytes sent
uint32 bytes_sent